'use client'
import Head from 'next/head'
import Button from '@mui/material/Button'
import { NextPage } from 'next'
import { ReactNode } from 'react'
import LayoutNotApp from 'src/views/layouts/LayoutNotApp'

type TProps = {

}

const Home: NextPage<TProps> = () => {

  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Button sx={{ margin: 6, width: "200px" }}>
      </Button>
    </>
  )
}

export default Home;

Home.getLayout = (page: ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>
